services:
  postgres:
    image: postgres:16

    restart: always

    environment:
      POSTGRES_USER: radarai
      POSTGRES_PASSWORD: radarai
      POSTGRES_DB: radarai

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
